<?xml version="1.0"?>
<package format="2">

  <name>go2_localization_guard</name>
  <version>0.1.0</version>

  <description>
    Sanity guard for global relocalization.
  </description>

  <maintainer email="nvidia@example.com">
    nvidia
  </maintainer>

  <license>BSD</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>roscpp</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>

  <export/>

</package>